### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by DeveloperLabUK** [jakemadness/discord-oauth2-login#1]
Hi, I'm having a small issue with the code, I'm not sure why but on the Discord login page, if the "Cancel" button is pressed, instead of returning to the previous page, it reloads the login page, "Authorise" works fine, it's just the "Cancel" button doesn't seem to do what it's supposed to.

![Screenshot_2019-08-24_10-25-14](https://user-images.githubusercontent.com/52407994/63635365-ddf94280-c659-11e9-8c26-5a0dd2c78963.png)

**Comment by iTURTL3** [comment]
Fixed by adding isset($_GET['error']) in the login.php file
